### PR TITLE
Add CodeQL security scanning

### PR DESCRIPTION
**Pull request by jhutchings1**
Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.

Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 

If you're interested in trying it out, you can merge this pull request to set up the Actions workflow. You can also get this set up yourself in any additional repositories in this organization by following these [instructions](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning)

### CODE REVIEW

**Comment by JonathanHenson** [comment]
The vast majority of this code base is in C, and the C code is far more likely to have a security vulnerability than would python. do we want to check that as well?

**Comment by jhutchings1** [comment]
@JonathanHenson I think that's a great idea. It's just going to require a bit of work getting a build up and running in Actions. I don't have experience with your project, so that's probably something better for someone more familiar with your code?

**Comment by JonathanHenson** [comment]
You don’t need anything other than a c compiler and cmake to run the build. Setup.py builds everything for you. Also it uses submodules so you’ll have to be sure to do a recursive clone.

**Comment by jhutchings1** [comment]
Thanks @JonathanHenson. It looks like the submodules were the issue, so I added that and now have C/C++ analysis going too.

**Comment by justinboswell** [comment]
This appears to be using python 2 to build in the autobuild script, which won't work as we've removed python 2 support. It should also be using `python3 -m pip install`, rather than `python setup.py`.

**Comment by jhutchings1** [comment]
This PR is a little out of date vs our current best practices so I'm going to close this out. If you're interested in taking this across the line, I'd suggest starting from the template in the Security tab (Security > Set up code scanning). Thanks!

**Pull request closed without merging**
